### PR TITLE
Join us button Placement

### PR DESCRIPTION
**Pull request by jigs1212**
Have adjusted placement of join us button placement.

### CODE REVIEW

**Comment by liginv** [comment]
Did you try running by `gulp serve` ?<br> Does the file transpile? because there wasn't any task written in gulp to handle **.less** files.

**Comment by jigs1212** [comment]
Less is automatically transpiled when I save the file. And is directly included as a seperate file.

**Comment by liginv** [comment]
Can you make the **.less code to .css** and add to **main.css** file? cause we don't want code spread in too many files.

**Comment by jigs1212** [comment]
Cancel this pull request.

**Pull request closed without merging**
